/*
 * This file is generated by jOOQ.
 */
package br.com.yurekesley.jooq;


import br.com.yurekesley.jooq.tables.Comments;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMENTS_POST_ID = Indexes0.COMMENTS_POST_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMMENTS_POST_ID = Internal.createIndex("POST_ID", Comments.COMMENTS, new OrderField[] { Comments.COMMENTS.POST_ID }, false);
    }
}
