/*
 * This file is generated by jOOQ.
 */
package br.com.yurekesley.jooq;


import br.com.yurekesley.jooq.tables.Comments;
import br.com.yurekesley.jooq.tables.Posts;


/**
 * Convenience access to all tables in test
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.COMMENTS</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>test.POSTS</code>.
     */
    public static final Posts POSTS = Posts.POSTS;
}
