/*
 * This file is generated by jOOQ.
*/
package br.com.yurekesley;


import br.com.yurekesley.tables.Comments;
import br.com.yurekesley.tables.FlywaySchemaHistory;
import br.com.yurekesley.tables.Posts;
import br.com.yurekesley.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.COMMENTS</code>.
     */
    public static final Comments COMMENTS = br.com.yurekesley.tables.Comments.COMMENTS;

    /**
     * The table <code>test.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = br.com.yurekesley.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>test.POSTS</code>.
     */
    public static final Posts POSTS = br.com.yurekesley.tables.Posts.POSTS;

    /**
     * The table <code>test.users</code>.
     */
    public static final Users USERS = br.com.yurekesley.tables.Users.USERS;
}
