/*
 * This file is generated by jOOQ.
*/
package br.com.yurekesley;


import br.com.yurekesley.tables.Comments;
import br.com.yurekesley.tables.FlywaySchemaHistory;
import br.com.yurekesley.tables.Posts;
import br.com.yurekesley.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = -1948304887;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.COMMENTS</code>.
     */
    public final Comments COMMENTS = br.com.yurekesley.tables.Comments.COMMENTS;

    /**
     * The table <code>test.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = br.com.yurekesley.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>test.POSTS</code>.
     */
    public final Posts POSTS = br.com.yurekesley.tables.Posts.POSTS;

    /**
     * The table <code>test.users</code>.
     */
    public final Users USERS = br.com.yurekesley.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comments.COMMENTS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Posts.POSTS,
            Users.USERS);
    }
}
